
[build]
  command = "CI= npm run build"
  publish="build"

[context.production]
  environment = { NODE_OPTIONS = "--max-old-space-size=4096"}
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200